version: '3.6'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: ecommerce

  app:
    image: node:16
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    environment:
      JWT_SECRET: doesntmatter
      DATABASE_URL: postgresql://admin:password@db:5432/ecommerce
    command: npm run dev

  prisma-studio:
    image: node:16
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 5555:5555
    command: npx prisma studio
